export const languages = {
    "english": {
        weekly: "WEEKLY",
        score: "SCORE",
        worldRankings: "WORLD RANKINGS",
        bestScore: "BEST SCORE",
        settings: "SETTINGS",
        profileName: "Profile Name",
        sounds: "SOUNDS",
        vibrations: "VIBRATIONS",
        theme: "THEME",
        rankings: "RANKINGS",
        appLogic: "APP LOGIC",
        privacy: "PRIVACY POLICY",
        terms: "TERMS OF USE",
        language: "LANGUAGE",
        removeAds: "REMOVE ADS",
        restore: "RESTORE PURCHASES",
        dark: "DARK",
        day: "DAY",
        ladies: "LADIES",
        bestOf: "best of",
        last24h: "LAST 24h",
        appText: "We are proud to present you with this enjoyable game. This game is a 9x9 field containing 81 cubes obtained by re-arranging the 3x3 matrix unit blocks consisting of 9 cubes as 3x3. You can place each component that we offer you in any suitable place in this field. If you place 9 cubes in the whole crosswise or longitudinally or in any unit matrix, the relevant field will explode and you will gain scores. The more you explode, the more scores you get. We wish you a good time."
    },
    "turkish": {
        weekly: "HAFTALIK",
        score: "PUAN",
        worldRankings: "DÜNYA SIRALAMALARI",
        bestScore: "EN İYİ PUAN",
        settings: "AYARLAR",
        profileName: "Profil İsmi",
        sounds: "SESLER",
        vibrations: "TİTREŞİMLER",
        theme: "TEMA",
        rankings: "SIRALAMALAR",
        appLogic: "UYGULAMA MANTIĞI",
        privacy: "GİZLİLİK POLİTİKASI",
        terms: "KULLANIM ŞARTLARI",
        language: "DİL",
        removeAds: "REKLAMLARI KALDIR",
        restore: "SATIN ALMALARI GERİ YÜKLE",
        dark: "KARANLIK",
        day: "GÜN",
        ladies: "HANIMLAR",
        bestOf: "en iyisi",
        last24h: "SON 24 saat",
        appText: "Sizlere bu keyifli oyunu sunmaktan gurur duyarız. Bu oyun 9 küpten oluşmuş 3x3’lük matrix birim blokların tekrar 3x3’lük dizilimi ile elde edilmiş 81 küp içeren 9x9’luk bir alandır. Sizlere sunduğumuz her bir bileşeni bu alanda uygun olan istediğiniz yere yerleştirebilirsiniz. Tüm alanda enine, boyuna ve herhangi bir birim matris te 9 adet küpü yerleştirirseniz, ilgili alan patlar ve size puan kazandırır. Ne kadar çok patlatırsanız o kadar çok puan kazanırsınız. İyi eğlenceler dileriz."
    },
    "spanish": {
        weekly: "SEMANALMENTE",
        score: "PUNTAJE",
        worldRankings: "CLASIFICACIONES MUNDIALES",
        bestScore: "MEJOR PUNTUACIÓN",
        settings: "AJUSTES",
        profileName: "Nombre de perfil",
        sounds: "SONIDOS",
        vibrations: "VIBRACIONES",
        theme: "TEMA",
        rankings: "CLASIFICACIONES",
        appLogic: "LÓGICA DE LA APLICACIÓN",
        privacy: "POLÍTICA DE PRIVACIDAD",
        terms: "TÉRMINOS DE USO",
        language: "IDIOMA",
        removeAds: "QUITAR ANUNCIOS",
        restore: "RESTAURAR LAS COMPRAS",
        dark: "OSCURO",
        day: "DÍA",
        ladies: "SEÑORAS",
        bestOf: "mejor de",
        last24h: "ÚLTIMAS 24h",
        appText: "Estamos orgullosos de presentarles este divertido juego. Este juego es un campo de 9x9 que contiene 81 cubos obtenidos al reorganizar los bloques de unidades de matriz de 3x3 que consisten en 9 cubos como 3x3. Puede colocar cada componente que le ofrecemos en cualquier lugar adecuado en este campo. Si coloca 9 cubos en el todo de forma transversal o longitudinal o en cualquier matriz unitaria, el campo correspondiente explotará y obtendrá puntajes. Cuanto más explotas, más puntuaciones obtienes. Le deseamos un buen momento."
    },
    "french": {
        weekly: "HEBDOMADAIRE",
        score: "SCORE",
        worldRankings: "CLASSEMENTS MONDIAUX",
        bestScore: "MEILLEUR SCORE",
        settings: "RÉGLAGES",
        profileName: "Nom de profil",
        sounds: "DES SONS",
        vibrations: "VIBRATIONS",
        theme: "THÈME",
        rankings: "CLASSEMENTS",
        appLogic: "LOGIQUE D'APPLICATION",
        privacy: "POLITIQUE DE CONFIDENTIALITÉ",
        terms: "CONDITIONS D'UTILISATION    ",
        language: "LANGUE",
        removeAds: "SUPPRIMEZ LA PUB",
        restore: "RESTAURATION DES ACHATS",
        dark: "FONCÉ",
        day: "JOURNÉE",
        ladies: "DAMES",
        bestOf: "meilleur de",
        last24h: "DERNIERS 24h",
        appText: "Nous sommes fiers de vous présenter ce jeu amusant. Ce jeu est un champ 9x9 contenant 81 cubes obtenus en réarrangeant les blocs unitaires matriciels 3x3 composés de 9 cubes en 3x3. Vous pouvez placer chaque composant que nous vous proposons à n'importe quel endroit approprié dans ce champ. Si vous placez 9 cubes dans l'ensemble transversalement ou longitudinalement ou dans n'importe quelle matrice unitaire, le champ concerné explosera et vous gagnerez des scores. Plus vous explosez, plus vous obtenez de points. Nous vous souhaitons un bon moment."
    },
    "german": {
        weekly: "WÖCHENTLICH",
        score: "PUNKTZAHL",
        worldRankings: "WELTRANGLISTEN",
        bestScore: "BESTES ERGEBNIS",
        settings: "DIE EINSTELLUNGEN",
        profileName: "Profilname",
        sounds: "GERÄUSCHE",
        vibrations: "SCHWINGUNGEN",
        theme: "THEMA",
        rankings: "RANGLISTEN",
        appLogic: "APP-LOGIK",
        privacy: "DATENSCHUTZ-BESTIMMUNGEN",
        terms: "NUTZUNGSBEDINGUNGEN",
        language: "SPRACHE",
        removeAds: "ANZEIGEN ENTFERNEN",
        restore: "KÄUFE WIEDERHERSTELLEN",
        dark: "DUNKEL",
        day: "TAG",
        ladies: "DAMEN",
        bestOf: "das beste von",
        last24h: "LETZTE 24 Std",
        appText: "Wir sind stolz darauf, Ihnen dieses unterhaltsame Spiel zu präsentieren. Dieses Spiel ist ein 9x9-Feld mit 81 Würfeln, das durch Neuanordnung der 3x3-Matrix-Einheitsblöcke, die aus 9 Würfeln bestehen, als 3x3 erhalten wird. Sie können jede Komponente, die wir Ihnen anbieten, an jedem geeigneten Ort in diesem Bereich platzieren. Wenn Sie 9 Würfel im Ganzen quer oder längs oder in einer beliebigen Einheitsmatrix platzieren, explodiert das entsprechende Feld und Sie erhalten Punkte. Je mehr Sie explodieren, desto mehr Punkte erhalten Sie. Wir wünschen Ihnen eine gute Zeit."
    },
    "italian": {
        weekly: "SETTIMANALMENTE",
        score: "PUNTO",
        worldRankings: "CLASSIFICHE MONDIALI",
        bestScore: "MIGLIOR PUNTEGGIO",
        settings: "IMPOSTAZIONI",
        profileName: "Nome del profilo",
        sounds: "SUONI",
        vibrations: "VIBRAZIONI",
        theme: "TEMA",
        rankings: "CLASSIFICHE",
        appLogic: "LOGICA APP",
        privacy: "POLITICA SULLA RISERVATEZZA",
        terms: "TERMINI DI UTILIZZO",
        language: "LINGUAGGIO",
        removeAds: "RIMUOVERE GLI ANNUNCI",
        restore: "RIPRISTINARE GLI ACQUISTI",
        dark: "SCURO",
        day: "GIORNO",
        ladies: "LE SIGNORE",
        bestOf: "il meglio di",
        last24h: "ULTIME 24h",
        appText: "Siamo orgogliosi di presentarvi questo divertente gioco. Questo gioco è un campo 9x9 contenente 81 cubi ottenuti riorganizzando i blocchi unità matrice 3x3 costituiti da 9 cubi come 3x3. Puoi posizionare ogni componente che ti offriamo in qualsiasi posto adatto in questo campo. Se metti 9 cubi nell'intero trasversalmente o longitudinalmente o in qualsiasi matrice di unità, il campo relativo esploderà e guadagnerai punteggi. Più esplodi, più punteggi ottieni. Ti auguriamo buon divertimento."
    },
    "russian": {
        weekly: "ЕЖЕНЕДЕЛЬНО",
        score: "СЧЕТ",
        worldRankings: "МИРОВОЙ РЕЙТИНГ",
        bestScore: "ЛУЧШИЙ РЕЗУЛЬТАТ",
        settings: "НАСТРОЙКИ",
        profileName: "Имя профиля",
        sounds: "ЗВУКИ",
        vibrations: "ВИБРАЦИИ",
        theme: "ТЕМА",
        rankings: "РЕЙТИНГ",
        appLogic: "ЛОГИКА ПРИЛОЖЕНИЯ",
        privacy: "ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ",
        terms: "УСЛОВИЯ ЭКСПЛУАТАЦИИ",
        language: "ЯЗЫК",
        removeAds: "УБРАТЬ РЕКЛАМУ",
        restore: "ВОССТАНОВИТЬ ПОКУПКИ",
        dark: "ТЕМНЫЙ",
        day: "ДЕНЬ",
        ladies: "ЖЕНЩИНЫ",
        bestOf: "лучшее из",
        last24h: "ПОСЛЕДНИЕ 24 часа",
        appText: "Мы рады представить вам эту увлекательную игру. Эта игра представляет собой поле 9x9, содержащее 81 куб, полученный путем перестановки блоков матрицы 3x3, состоящих из 9 кубов, как 3x3. Вы можете разместить каждый компонент, который мы вам предлагаем, в любом подходящем месте в этом поле. Если вы поместите 9 кубиков в целом поперек или вдоль или в любую единичную матрицу, соответствующее поле взорвется, и вы получите очки. Чем больше вы взорветесь, тем больше очков получите. Желаем вам хорошо провести время."
    }
}